# 1

In [ ]:
import numpy

def arrays(arr):
    return numpy.array(arr[::-1],float)
    # complete this function
    # use numpy.array

arr = input().strip().split(' ')

# 2

In [9]:
b=numpy.array(input().split(),int)
print(b)
print(type(b))
b.shape=(2,2)
print(b)

3 2 1 5
[3 2 1 5]
<class 'numpy.ndarray'>
[[3 2]
 [1 5]]


# 3

In [15]:
n, m = map(int, input().split())
array = numpy.array([input().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

3 2
2 3 4
1 2 3
1 3 2
[[2 1 1]
 [3 2 3]
 [4 3 2]]
[2 3 4 1 2 3 1 3 2]


# 4

In [ ]:
a, b, c = map(int,input().split())
arrA = numpy.array([input().split() for _ in range(a)],int)
arrB = numpy.array([input().split() for _ in range(b)],int)
print(numpy.concatenate((arrA, arrB), axis = 0))


# 5

In [3]:
import numpy
nums = tuple(map(int, input().split()))
print (numpy.zeros(nums, dtype = numpy.int))
print (numpy.ones(nums, dtype = numpy.int))


2 2
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]


# 6

In [13]:
numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))

2 2
[[ 1.  0.]
 [ 0.  1.]]


# 7

In [18]:
n, m = map(int, input().split())
a, b = (numpy.array([input().split() for _ in range(n)], dtype=int) for _ in range(2))
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

2 4
1 3 2
12 34 23
1 4 2
5 3 2
[[ 2  7  4]
 [17 37 25]]
[[ 0 -1  0]
 [ 7 31 21]]
[[  1  12   4]
 [ 60 102  46]]
[[ 1  0  1]
 [ 2 11 11]]
[[0 3 0]
 [2 1 1]]
[[     1     81      4]
 [248832  39304    529]]
